data:
  data_path: "gs://bin_for_aiops/GambleMaster/LuxuryDice/luxury_dice.npz"
  time_length: 15
  train_test_split: 0.8

train:
  batch_size: 256
  epoch: 3000

test:
  batch_size: 128

model:
  loss: "MDN"    # "MeanSquaredError", "MDF"
  metrics: "MDN"
  focal_weight: 5

optimizer:
  method: "adam"
  learning_rate: 1e-4

weights:
  simulation: "weights/best_luxury_dice_simulation_model.tf"
